CREATE TABLE APP.PERSON
(
  ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
      (START WITH 1, INCREMENT BY 1),
  FIRSTNAME varchar(50) NOT NULL,
  LASTNAME varchar(100) NOT NULL,
  LOGIN varchar(20) NOT NULL UNIQUE,
  EMAIL varchar(45) NOT NULL UNIQUE,
  PASSWORD varchar(100),
  DTYPE varchar(31)
);
CREATE UNIQUE INDEX SQL_PERSON_EMAIL_INDEX ON APP.PERSON(EMAIL);
CREATE UNIQUE INDEX SQL_PERSON_ID_INDEX ON APP.PERSON(ID);
CREATE TABLE APP.GROUPS
(
   ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
       (START WITH 1, INCREMENT BY 1),
   GROUPNAME varchar(50) NOT NULL,
   DESCRIPTION varchar(300)
);
CREATE TABLE APP.PERSON_GROUPS
(
  GROUPS_ID int NOT NULL,
  LOGIN varchar(20) NOT NULL
);
ALTER TABLE APP.PERSON_GROUPS
ADD CONSTRAINT FK_PERSON_GROUPS_PERSON
FOREIGN KEY (EMAIL)
REFERENCES APP.PERSON(EMAIL);
ALTER TABLE APP.PERSON_GROUPS
ADD CONSTRAINT FK_PERSON_GROUPS_GROUPS
FOREIGN KEY (GROUPS_ID)
REFERENCES APP.GROUPS(ID);
CREATE INDEX SQL_PERSONGROUPS_EMAIL_INDEX ON APP.PERSON_GROUPS(EMAIL);
CREATE INDEX SQL_PERSONGROUPS_ID_INDEX ON APP.PERSON_GROUPS(GROUPS_ID);


INSERT INTO APP.PERSON(FIRSTNAME, LASTNAME, LOGIN, EMAIL, PASSWORD, DTYPE)
VALUES('root', 'root', 'root', 'root@ecologu.com', '63a9f0ea7bb98050796b649e85481845', 'Administrator');

INSERT INTO APP.GROUPS(NAME, DESCRIPTION)
VALUES ('USERS', 'Users of the application');
INSERT INTO APP.GROUPS (NAME, DESCRIPTION) 
VALUES ('ADMINS', 'Administrators of the application');

INSERT INTO APP.PERSON_GROUPS (GROUPS_ID, EMAIL) 
VALUES (2,'root');
