CREATE TABLE APP.PERSON
(
  ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
      (START WITH 1, INCREMENT BY 1),
  FIRSTNAME varchar(50) NOT NULL,
  LASTNAME varchar(100) NOT NULL,
  EMAIL varchar(45) NOT NULL UNIQUE,
  PASSWORD varchar(100),
  DTYPE varchar(31)
);
CREATE UNIQUE INDEX SQL_PERSON_EMAIL_INDEX ON APP.PERSON(EMAIL);
CREATE UNIQUE INDEX SQL_PERSON_ID_INDEX ON APP.PERSON(ID);
CREATE TABLE APP.GROUPS
(
   ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
       (START WITH 1, INCREMENT BY 1),
   GROUPNAME varchar(50) NOT NULL,
   DESCRIPTION varchar(300)
);
CREATE TABLE APP.PERSON_GROUPS
(
  GROUPS_ID int NOT NULL,
  EMAIL varchar(45) NOT NULL
);
ALTER TABLE APP.PERSON_GROUPS
ADD CONSTRAINT FK_PERSON_GROUPS_PERSON
FOREIGN KEY (EMAIL)
REFERENCES APP.PERSON(EMAIL);
ALTER TABLE APP.PERSON_GROUPS
ADD CONSTRAINT FK_PERSON_GROUPS_GROUPS
FOREIGN KEY (GROUPS_ID)
REFERENCES APP.GROUPS(ID);
CREATE INDEX SQL_PERSONGROUPS_EMAIL_INDEX ON APP.PERSON_GROUPS(EMAIL);
CREATE INDEX SQL_PERSONGROUPS_ID_INDEX ON APP.PERSON_GROUPS(GROUPS_ID);
