CREATE TABLE APP.USERTABLE
(
    USERID VARCHAR(20) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(20)
);

CREATE TABLE APP.GROUPTABLE
(
    USERID VARCHAR(20) NOT NULL PRIMARY KEY,
    GROUPID VARCHAR(20)
);

INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('test', 'test');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('test', 'ADMINS');
INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('Hugo', 'hugo');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('Hugo', 'ADMINS');
INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('Raed', 'raed');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('Raed', 'ADMINS');
INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('Sam', 'sam');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('Sam', 'ADMINS');
INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('Elodie', 'elodie');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('Elodie', 'ADMINS');
INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('Yaxi', 'yaxi');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('Yaxi', 'ADMINS');
INSERT INTO APP.USERTABLE(USERID, PASSWORD) VALUES('Alexandre', 'alexandre');
INSERT INTO APP.GROUPTABLE(USERID, GROUPID) VALUES('Alexandre', 'ADMINS');
